inherit_from:
  - .rubocop_todo.yml
  - .rubocop_rails.yml
  - .rubocop_rspec.yml
  - .rubocop_strict.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml



AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - '**/Gemfile'
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'

Layout/LineLength:
  Max: 130

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
