version: '3'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgresdb
      DATABASE_NAME: radiar_development
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      ROLLBAR_ENV: development

  sidekiq:
    build: .
    links:
      - redis
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgresdb
      DATABASE_NAME: radiar_development
      SIDEKIQ: 1
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      ROLLBAR_ENV: development
    env_file:
      - .env

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  database:
    image: postgres:12.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdb
      POSTGRES_DB: radiar_development
