version: '3'

services:
  app:
    build: .
    restart: always
    networks:
      - web
      - default
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    links:
      - redis
    labels:
      - traefik.http.routers.dashboard.rule=Host(`radiar.deimel.de`)

  sidekiq:
    build: .
    restart: always
    networks:
      - default
    links:
      - redis
    env_file:
      - .env
    environment:
      SIDEKIQ: 1

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    networks:
      - default
    ports:
      - '6379:6379'

networks:
  web:
    external: true
